#!/bin/bash
set -ex

# ------------------------------------------------------------------------------
# Download bitcoin release from github
# ------------------------------------------------------------------------------

echo "Fetching bitcoin version: $BITCOIN_VERSION"
curl -L https://github.com/bitcoin/bitcoin/archive/refs/tags/v$BITCOIN_VERSION.tar.gz | tar -zx --strip-components=1


# ------------------------------------------------------------------------------
# Compile
# ------------------------------------------------------------------------------

echo "Building bitcoin source..."
./autogen.sh 
./configure --disable-wallet
make 
make install