version: "3.9"

# ------------------------------------------------------------------------------
# Services
# ------------------------------------------------------------------------------

# Bare bones validator setup process
# https://www.cleverti.com/blog/how-to-become-an-eth2-validator-step-by-step-practical-tutorial/

# Will need to run this to generate validator keys
# https://github.com/ethereum/eth2.0-deposit-cli

services:
  #
  # --- Go-Ethereum
  # https://geth.ethereum.org/docs/interface/command-line-options
  # https://geth.ethereum.org/docs/install-and-build/installing-geth
  #
  # Reset database
  #   docker-compose run goeth removedb
  # Prune db https://gist.github.com/yorickdowne/3323759b4cbf2022e191ab058a4276b2
  #   docker-compose run goeth snapshot prune-state
  goeth:
    image: ethereum/client-go:stable
    ports:
      - 30303:30303  # TCP and UDP, used by the P2P protocol running the network
    expose:
      - 8545  # TCP, used by the HTTP based JSON RPC API
    volumes:
      - geth-data:/root/.ethereum
    command: "-syncmode snap --http --http.addr 0.0.0.0 --http.vhosts '*'"
    restart: always
  
  #
  # --- Beacon chain
  # https://docs.prylabs.network/docs/install/install-with-docker
  #
  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    ports:
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - beacon-chain-data:/data
    command: "--datadir=/data --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --http-web3provider=http://goeth:8545 --accept-terms-of-use"
    restart: always


# ------------------------------------------------------------------------------
# Volumes
# ------------------------------------------------------------------------------

volumes:
  # Pretty big, use 4TB disk
  geth-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/btcbigdisk/geth
  # Beacon chain volume. How big is 
  beacon-chain-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/btcbigdisk/beacon