# Generated by Django 3.2.7 on 2021-10-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0004_auto_20211006_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='transaction_count',
            new_name='tx_count',
        ),
    ]
