# Generated by Django 3.2.7 on 2021-10-08 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0008_auto_20211007_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='utxo',
            name='tx_in',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='utxo_created_set', to='btcexplore.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utxo',
            name='tx_out',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='utxo_spent_set', to='btcexplore.transaction'),
            preserve_default=False,
        ),
    ]
