# Generated by Django 3.2.7 on 2021-10-08 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0009_auto_20211007_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxo',
            name='tx_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utxo_spent_set', to='btcexplore.transaction'),
        ),
    ]
