# Generated by Django 3.2.7 on 2021-10-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0011_alter_transaction_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxo',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btcexplore.wallet'),
        ),
    ]
