# Generated by Django 3.2.7 on 2021-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0012_alter_utxo_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxo',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
    ]
