# Generated by Django 3.2.7 on 2021-10-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0014_alter_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODLWaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('band_24h_count', models.IntegerField(default=0)),
                ('band_24h_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_1d_count', models.IntegerField(default=0)),
                ('band_1d_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_1w_count', models.IntegerField(default=0)),
                ('band_1w_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_1m_count', models.IntegerField(default=0)),
                ('band_1m_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_3m_count', models.IntegerField(default=0)),
                ('band_3m_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_6m_count', models.IntegerField(default=0)),
                ('band_6m_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_1y_count', models.IntegerField(default=0)),
                ('band_1y_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_2y_count', models.IntegerField(default=0)),
                ('band_2y_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_3y_count', models.IntegerField(default=0)),
                ('band_3y_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_5y_count', models.IntegerField(default=0)),
                ('band_5y_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_7y_count', models.IntegerField(default=0)),
                ('band_7y_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('band_10y_count', models.IntegerField(default=0)),
                ('band_10y_sum', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
            ],
        ),
    ]
