# Generated by Django 3.2.7 on 2021-10-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0015_hodlwaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodlwaves',
            name='band_24h_count',
        ),
        migrations.RemoveField(
            model_name='hodlwaves',
            name='band_24h_sum',
        ),
        migrations.AddField(
            model_name='hodlwaves',
            name='band_over_10y_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hodlwaves',
            name='band_over_10y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_10y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_1d_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_1m_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_1w_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_1y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_2y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_3m_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_3y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_5y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_6m_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hodlwaves',
            name='band_7y_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
    ]
