#!/bin/bash
set -ex

cd lndconnect/

go mod edit -require github.com/lightningnetwork/lnd@v0.12.1-beta
go get github.com/btcsuite/btcutil@v1.0.3-0.20201208143702-a53e38424cce
go get github.com/lightningnetwork/lnd/tor@v0.12.1-beta
go get github.com/lightningnetwork/lnd/tor@v0.12.1-beta
go get github.com/mattn/go-isatty@v0.0.12

go build

mv lndconnect /usr/local/bin/lndconnect