#!/bin/bash
set -e

# ------------------------------------------------------------------------------
#
# This script checks the bitcoin data volume for necessary configuration, adding
# it if not exists.
#
# ------------------------------------------------------------------------------

# Add a wallet named `wallet`
if [ ! -d "$HOME/.bitcoin/wallet" ]
then
    echo "Wallet not found, creating..."
    bitcoin-cli createwallet "wallet"
    # TODO: wallet security
    # create random password, write to file on volume? 
    echo "Wallet created!"
    
fi

# Add bitcoin.conf, defining operating behavior of our bitcoind daemon
if [ ! -e "$HOME/.bitcoin/bitcoin.conf" ]
then
    mkdir -p $HOME/.bitcoin

    echo "Creating bitcoin.conf"
    
    cat <<EOF > $HOME/.bitcoin/bitcoin.conf
#---------------------------------------
# bitcoin.conf
#---------------------------------------
# tells bitcoind to accept JSON-RPC commands
server=1

# Has to accept non-localhost because of Docker networking
rpcallowip=0.0.0.0/0
rpcbind=:8332

# RPC username/password
rpcuser=bitcoinrpcuser
rpcpassword=`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`

# Location of our wallet
wallet=$HOME/.bitcoin/wallet
EOF

    cat $HOME/.bitcoin/bitcoin.conf
fi

# Use exec to replace this shell with the CMD process
exec "$@"
