# Generated by Django 3.2.7 on 2021-09-30 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('hash', models.CharField(max_length=64)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcexplore.block')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
