# Generated by Django 3.2.7 on 2021-10-05 20:31

import btcexplore.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(unique=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('time', models.DateTimeField(null=True)),
                ('transactions_created', models.BooleanField(default=False)),
                ('last', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='btcexplore.block')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64)),
                ('vin', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('vout', models.JSONField(decoder=btcexplore.models.Transaction.VoutDecoder, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='btcexplore.block')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('transaction_count', models.IntegerField()),
                ('total_received', models.DecimalField(decimal_places=8, max_digits=15)),
                ('total_sent', models.DecimalField(decimal_places=8, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Utxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=8, max_digits=15)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcexplore.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcexplore.wallet')),
            ],
        ),
    ]
