# Generated by Django 3.2.7 on 2021-10-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
