# Generated by Django 3.2.7 on 2021-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0002_auto_20211006_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
