# Generated by Django 3.2.7 on 2021-10-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0003_alter_wallet_transaction_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_sent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
    ]
