# Generated by Django 3.2.7 on 2021-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0004_auto_20211001_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=64),
        ),
    ]
