# Generated by Django 3.2.7 on 2021-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0005_alter_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=64),
        ),
    ]
