# Generated by Django 3.2.7 on 2021-10-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0006_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utxo',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcexplore.block'),
        ),
    ]
