# Generated by Django 3.2.7 on 2021-10-01 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0006_alter_transaction_txid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='data',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='btcexplore.block'),
        ),
    ]
