# Generated by Django 3.2.7 on 2021-10-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0007_auto_20211001_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='next_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_block', to='btcexplore.block'),
        ),
    ]
