# Generated by Django 3.2.7 on 2021-10-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0008_block_next_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='next_block',
        ),
        migrations.AddField(
            model_name='block',
            name='last',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='btcexplore.block'),
        ),
    ]
