# Generated by Django 3.2.7 on 2021-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0009_auto_20211002_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
