# Generated by Django 3.2.7 on 2021-10-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0010_alter_utxo_tx_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
