# Generated by Django 3.2.7 on 2021-10-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0010_block_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vin',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='vout',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Utxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcexplore.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcexplore.wallet')),
            ],
        ),
    ]
