# Generated by Django 3.2.7 on 2021-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0012_auto_20211004_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=64),
        ),
    ]
