# Generated by Django 3.2.7 on 2021-10-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0013_alter_utxo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
