# Generated by Django 3.2.7 on 2021-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcexplore', '0017_rename_hodlwaves_hodlwave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodlwave',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
